# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('useremail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(default='password', max_length=255)),
            ],
        ),
    ]
