# Generated by Django 5.1.1 on 2024-09-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='useremail',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
