# Generated by Django 5.1.1 on 2024-09-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgresql', '0002_alter_user_useremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
